### ISSUE TITLE
Add gh-pages branch to allow adding to Cydia.

### ISSUE THREAD

**Issue by ZenIsBestWolf** [Chr0nicT/Nepeta-Mirror#1]
Add the gh-pages branch so users can add to Cydia/Sileo/Zebra with https://chr0nict.github.io/nepeta-mirror/

**Comment by 10Meisterbaelle** [comment]
There should be this link added:
https://cydia.saurik.com/api/share#?source=https://chr0nict.github.io/Nepeta-Mirror

**Comment by debouncedgit** [comment]
You should already be able to add this repository to any given package manager. If you cant it's a problem on your end.
