### ISSUE TITLE
Copyright Infringement

### ISSUE THREAD

**Issue by realleyriley** [Chr0nicT/Nepeta-Mirror#4]
Hey I just want to make sure that this repository is not infringing on anyone's copyright material. 

In the United States, authors have initial ownership: 
```
(a) Initial Ownership.—Copyright in a work protected under this title
vests initially in the author or authors of the work. The authors of a joint work
are coowners of copyright in the work.
```
[Source](https://www.copyright.gov/title17/title17.pdf).

So I'm assuming by some means that you have the right to distribute the work from Nepeta?

I can see that in the README you say this is not your work, but saying that is pointless if what you are doing does not fall under fair use. Fair use is in section 107 of [US Copyright Law](https://www.copyright.gov/title17/title17.pdf).

**Comment by Chr0nicT** [comment]
The original developer has made it clear that the work is okay to be redistributed. The work was also under the MIT license in the beginning.
